// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import DragHomeController from "./drag_home_controller"
application.register("drag-home", DragHomeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import PricingController from "./pricing_controller"
application.register("pricing", PricingController)
