meta_name: "Items to borrow"
meta_title: "Nearby - items to borrow"
meta_description: "Neighboor are getting better with Nearby. Share or lend items to your fellow citizen. Make your project possible without spending a dime,"
meta_image: "meta-image.jpg"
